In [ ]:
#변수간 관계 확인
#분석모형 구축시 유의사항
#변수의 유의성 검증 후 유의성이 높은 최소한의 변수들로 분석 모형을 검증
#분석 모형을 구축하는 데에는 일반화 오류와 훈련 오류라는 두 가지종류의 오류가 발생

#일반화 오류 - 
#훈련 오류

In [2]:
#무작위 추출을 통해 7:3 비율로 train/test 데이터 준비
s <- read.table('c:/Java/phone-02.csv', header=F, sep=',')
s

   V1   V2   V3  V4 V5  V6 V7  V8  V9
1  2015 2015 5.0 45 173 75  60 500  100
2  2014 2015 4.5 27 176 59  70  30   50
3  2015 2015 5.0 29 183 65 120 300  200
4  2015 2016 5.0 28 172 63  80  60  190
5  2015 2015 5.0 24 179 65  90  30  500
6  2016 2016 5.5 34 175 73  80 480  160
7  2016 2016 6.0 40 169 77  60 300  170
8  2014 2014 5.0 40 182 82  50  60   50
9  2014 2014 4.5 30 175 70 100  90  300
10 2015 2015 5.0 42 177 79  40 480   30
11 2014 2014 4.5 32 167 62 130 300  400
12 2015 2015 5.5 37 171 70  90 360  200
13 2015 2015 5.5 35 173 69  60 120  150
14 2015 2016 6.0 41 181 88  60 120  130
15 2015 2015 5.5 40 178 89  70  60  140
16 2015 2015 5.0 35 169 70  50  90   80
17 2016 2016 5.5 35 184 72  90  90   70
18 2016 2016 6.0 34 176 71  90  60  130
19 2015 2015 4.5 29 188 83 140 240  600
20 2016 2016 5.5 30 175 70  50 120   50
21 2015 2015 5.5 32 177 68  70 120  300
22 2016 2016 5.5 25 182 73  60  60  300
23 2015 2015 5.0 26 179 80 180  30 1100
24 2016 2016 6.0 25 177 76 120  90  700

In [3]:
tr <- sample(nrow(s), replace=F, size=nrow(s)*0.7)

In [4]:
s_train <- s[tr, ]
s_test <- s[-tr, ]

In [5]:
#회귀모형 구축 - 회귀식 작성
lm(s_train[,9]~s_train[,7], data=s_train)

#y = -309 + (6.865 * x)

Call:
lm(formula = s_train[, 9] ~ s_train[, 7], data = s_train)

Coefficients:
 (Intercept)  s_train[, 7]
    -309.135         6.865

In [8]:
#회귀식을 함수로 만들고 시험 데이터로 확인
lrm <- function(x) {
    -309 + (6.865 * x)
}

test_result <- lrm(s_test[,7])
test_result

[1] 171.55 514.80 240.20 -34.40 102.90 102.90 171.55 171.55

In [11]:
#RMSE 계산
rmse <- sum(abs(s_test[,7] - lrm(s_test[, 7])))/sqrt(nrow(s_test))

rmse

[1] 360.5714

In [13]:
#for 구문 
#데이터 정제하기
#데이터 유형 추출 - which
l2016 <- which(s[,1]==2016) #2016 출시상품 index로 표시
s[l2016, ] #2016출시상품 출력

#특정범위 데이터 추출
gt_500 <- s[,9] > 500 #일일 데이터 사용량 500mb이상
s[gt_500, ]

   V1   V2   V3  V4 V5  V6 V7  V8  V9
6  2016 2016 5.5 34 175 73  80 480 160
7  2016 2016 6.0 40 169 77  60 300 170
17 2016 2016 5.5 35 184 72  90  90  70
18 2016 2016 6.0 34 176 71  90  60 130
20 2016 2016 5.5 30 175 70  50 120  50
22 2016 2016 5.5 25 182 73  60  60 300
24 2016 2016 6.0 25 177 76 120  90 700

   V1   V2   V3  V4 V5  V6 V7  V8  V9
19 2015 2015 4.5 29 188 83 140 240  600
23 2015 2015 5.0 26 179 80 180  30 1100
24 2016 2016 6.0 25 177 76 120  90  700

In [15]:
#일일 데이터사용량이 400MB 이상인 샘플
gt_400 <- s[,9] >= 400
s[gt_400, ]

   V1   V2   V3  V4 V5  V6 V7  V8  V9
5  2015 2015 5.0 24 179 65  90  30  500
11 2014 2014 4.5 32 167 62 130 300  400
19 2015 2015 4.5 29 188 83 140 240  600
23 2015 2015 5.0 26 179 80 180  30 1100
24 2016 2016 6.0 25 177 76 120  90  700

In [ ]:
#KNN 알고리즘 군집화
#차종 마력 경기용차여부, 뿌른지여부
#혼다어코드, 180, F, F
#유고, 500, T, T
#드롤리안, 200, T, F
#쉐보레카미로, 400, T, ? 어떻게 군집화할 것인가?

#유클리드 거리측정 이용 : sqrt((p1-p3)**2 + (p2-p4)**2)
#차종, 마력, 빠른지여부
#혼다어코드, 180(p1), 0()(p2) 
#유고, 500(p3), 1(p4)
#드롤리안, 200, 0
#쉬보레카미로 400, ?

In [17]:
km <- kmeans(s[,9],5)
km

K-means clustering with 5 clusters of sizes 7, 4, 9, 3, 1

Cluster means:
        [,1]
1   61.42857
2  325.00000
3  163.33333
4  600.00000
5 1100.00000

Clustering vector:
 [1] 1 1 3 3 4 3 3 1 2 1 2 3 3 3 3 1 1 3 4 1 2 2 5 4

Within cluster sum of squares by cluster:
[1]  3285.714  7500.000  6400.000 20000.000     0.000
 (between_SS / total_SS =  97.5 %)

Available components:

[1] "cluster"      "centers"      "totss"        "withinss"     "tot.withinss"
[6] "betweenss"    "size"         "iter"         "ifault"

In [22]:
km5 <- kmeans(s[,9],5)
km3 <- kmeans(s[,9],3)
km5
km3

K-means clustering with 5 clusters of sizes 7, 3, 1, 9, 4

Cluster means:
        [,1]
1   61.42857
2  600.00000
3 1100.00000
4  163.33333
5  325.00000

Clustering vector:
 [1] 1 1 4 4 2 4 4 1 5 1 5 4 4 4 4 1 1 4 2 1 5 5 3 2

Within cluster sum of squares by cluster:
[1]  3285.714 20000.000     0.000  6400.000  7500.000
 (between_SS / total_SS =  97.5 %)

Available components:

[1] "cluster"      "centers"      "totss"        "withinss"     "tot.withinss"
[6] "betweenss"    "size"         "iter"         "ifault"

K-means clustering with 3 clusters of sizes 7, 16, 1

Cluster means:
       [,1]
1  442.8571
2  118.7500
3 1100.0000

Clustering vector:
 [1] 2 2 2 2 1 2 2 2 1 2 1 2 2 2 2 2 2 2 1 2 1 1 3 1

Within cluster sum of squares by cluster:
[1] 157142.9  50575.0      0.0
 (between_SS / total_SS =  85.8 %)

Available components:

[1] "cluster"      "centers"      "totss"        "withinss"     "tot.withinss"
[6] "betweenss"    "size"         "iter"         "ifault"

In [23]:
km5$cluster #군집 벡터값 출력

 [1] 1 1 4 4 2 4 4 1 5 1 5 4 4 4 4 1 1 4 2 1 5 5 3 2

In [24]:
km3$center #군집 벡터값 출력

  [,1]
1  442.8571
2  118.7500
3 1100.0000

In [26]:
s_km3 <- cbind(s, km$cluster)
s_km3

   V1   V2   V3  V4 V5  V6 V7  V8  V9   km$cluster
1  2015 2015 5.0 45 173 75  60 500  100 1
2  2014 2015 4.5 27 176 59  70  30   50 1
3  2015 2015 5.0 29 183 65 120 300  200 3
4  2015 2016 5.0 28 172 63  80  60  190 3
5  2015 2015 5.0 24 179 65  90  30  500 4
6  2016 2016 5.5 34 175 73  80 480  160 3
7  2016 2016 6.0 40 169 77  60 300  170 3
8  2014 2014 5.0 40 182 82  50  60   50 1
9  2014 2014 4.5 30 175 70 100  90  300 2
10 2015 2015 5.0 42 177 79  40 480   30 1
11 2014 2014 4.5 32 167 62 130 300  400 2
12 2015 2015 5.5 37 171 70  90 360  200 3
13 2015 2015 5.5 35 173 69  60 120  150 3
14 2015 2016 6.0 41 181 88  60 120  130 3
15 2015 2015 5.5 40 178 89  70  60  140 3
16 2015 2015 5.0 35 169 70  50  90   80 1
17 2016 2016 5.5 35 184 72  90  90   70 1
18 2016 2016 6.0 34 176 71  90  60  130 3
19 2015 2015 4.5 29 188 83 140 240  600 4
20 2016 2016 5.5 30 175 70  50 120   50 1
21 2015 2015 5.5 32 177 68  70 120  300 2
22 2016 2016 5.5 25 182 73  60  60  300 2
23 2015 2015 5.0 26 179 80 180  30 1100 5
24 2016 2016 6.0 25 177 76 120  90  700 4

In [35]:
km5$cluster #군집 벡터값 출력\
km5$center #군집 벡터값 평균
km5_cluster <- km5$cluster


for(i in 1:5) {
    km5_cluster[km5_cluster == i] <- km5$centers[i]
    }

 [1] 1 1 4 4 2 4 4 1 5 1 5 4 4 4 4 1 1 4 2 1 5 5 3 2

  [,1]
1   61.42857
2  600.00000
3 1100.00000
4  163.33333
5  325.00000

In [36]:
s_km5 <- cbind(s, km5_cluster)#평균값으로 대체
s_km5

   V1   V2   V3  V4 V5  V6 V7  V8  V9   km5_cluster
1  2015 2015 5.0 45 173 75  60 500  100   61.42857
2  2014 2015 4.5 27 176 59  70  30   50   61.42857
3  2015 2015 5.0 29 183 65 120 300  200  163.33333
4  2015 2016 5.0 28 172 63  80  60  190  163.33333
5  2015 2015 5.0 24 179 65  90  30  500  600.00000
6  2016 2016 5.5 34 175 73  80 480  160  163.33333
7  2016 2016 6.0 40 169 77  60 300  170  163.33333
8  2014 2014 5.0 40 182 82  50  60   50   61.42857
9  2014 2014 4.5 30 175 70 100  90  300  325.00000
10 2015 2015 5.0 42 177 79  40 480   30   61.42857
11 2014 2014 4.5 32 167 62 130 300  400  325.00000
12 2015 2015 5.5 37 171 70  90 360  200  163.33333
13 2015 2015 5.5 35 173 69  60 120  150  163.33333
14 2015 2016 6.0 41 181 88  60 120  130  163.33333
15 2015 2015 5.5 40 178 89  70  60  140  163.33333
16 2015 2015 5.0 35 169 70  50  90   80   61.42857
17 2016 2016 5.5 35 184 72  90  90   70   61.42857
18 2016 2016 6.0 34 176 71  90  60  130  163.33333
19 2015 2015 4.5 29 188 83 140 240  600  600.00000
20 2016 2016 5.5 30 175 70  50 120   50   61.42857
21 2015 2015 5.5 32 177 68  70 120  300  325.00000
22 2016 2016 5.5 25 182 73  60  60  300  325.00000
23 2015 2015 5.0 26 179 80 180  30 1100 1100.00000
24 2016 2016 6.0 25 177 76 120  90  700  600.00000